# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ray
tagline:          'UCLA MATH'
description:      'CS & Math Stuff'
url:              http://Ritwik7631.github.io
baseurl:          ''
kramdown:
  parse_block_html: true

author:
  name:           'Ritwik Kumar'

paginate:         10

# Custom vars
version:          2.1.0

github:           https://github.com/Ritwik7631

plugins:
  - jekyll-archives
  - jekyll-seo-tag
